'use strict';

const nodemailer = require('nodemailer');
const { EMAIL_CONFIG } = require('../../config');
const { logAudit } = require('../audit/logAudit');

/**
 * Sends the Rent Reconciliation report via email.
 * @param {Buffer} pdfBuffer - The PDF content as a buffer.
 * @param {string} dateStr - The current date string for the subject.
 */
async function sendReconciliationEmail(pdfBuffer, dateStr) {
    const emailTo = EMAIL_CONFIG.recipient;

    if (!EMAIL_CONFIG.user || !EMAIL_CONFIG.pass) {
        console.warn('Email config missing, skipping email notification');
        return;
    }

    const transporter = nodemailer.createTransport({
        service: EMAIL_CONFIG.service,
        auth: {
            user: EMAIL_CONFIG.user,
            pass: EMAIL_CONFIG.pass,
        },
    });

    const mailOptions = {
        from: EMAIL_CONFIG.user,
        to: emailTo,
        subject: `Rent Reconciliation Report - ${dateStr}`,
        text: `Please find attached the automated Rent Reconciliation Report for ${dateStr}.`,
        html: `
      <h2>Rent Reconciliation Report</h2>
      <p>Please find attached the automated Rent Reconciliation Report for <b>${dateStr}</b>.</p>
      <br>
      <p><i>Generated by HIVE NY Automation</i></p>
    `,
        attachments: [
            {
                filename: `Rent_Reconciliation_Report_${dateStr.replace(/[\/:]/g, '-')}.pdf`,
                content: pdfBuffer,
            },
        ],
    };

    try {
        await transporter.sendMail(mailOptions);
        console.log(`Reconciliation report emailed successfully to: ${emailTo}`);
        
        // Audit log for successful email send (mutation complete)
        try {
            await logAudit({
                user: 'RECONCILIATION_SERVICE',
                sheet: 'Rent_Reconciliation',
                cell: 'N/A',
                oldValue: 'Report not sent',
                newValue: `Reconciliation report sent to ${emailTo}`,
                source: 'RECONCILIATION_EMAIL',
            });
        } catch (err) {
            console.warn('Audit log failed:', err.message);
        }
    } catch (error) {
        console.error('Failed to send reconciliation email:', error.message);
        throw error;
    }
}

module.exports = { sendReconciliationEmail };
